# Generated by Django 5.0.2 on 2024-02-26 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_desc_todo_description_rename_name_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
